apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: niximgs
build:
  artifacts:
    - custom:
        buildCommand:
          nix run github:shikanime-studio/nix-containers -- skaffold build
      image: ghcr.io/shikanime-labs/machines/catbox
