{
  config,
  pkgs,
  lib,
  ...
}:

{
  imports = [
    ./rpi.nix
  ];

  # Kernelboot bootloader: the Pi 5 firmware loads kernel.img directly
  # from the firmware partition, bypassing the extlinux layer.
  # The extlinux-compatible module stays enabled (sd-image-aarch64.nix
  # requires it for populateRootCommands), but we override the root
  # population to skip extlinux since the firmware boots kernel.img directly.
  boot.loader.generic-extlinux-compatible.enable = lib.mkDefault true;

  boot.kernelParams = [
    "cgroup_enable=cpuset"
    "cgroup_enable=memory"
    "cgroup_memory=1"
  ];

  # The firmware partition layout for kernelboot:
  #   /boot/firmware/kernel.img    — the kernel image
  #   /boot/firmware/initrd        — the initramfs
  #   /boot/firmware/cmdline.txt   — kernel command line
  #   /boot/firmware/*.dtb         — device tree blobs
  #   /boot/firmware/overlays/     — DTB overlays
  #   /boot/firmware/config.txt    — firmware configuration
  sdImage.populateFirmwareCommands = ''
    # Copy firmware blobs (bootcode.bin, start*.elf, fixup*.dat)
    (cd ${pkgs.raspberrypifw}/share/raspberrypi/boot && cp bootcode.bin fixup*.dat start*.elf $NIX_BUILD_TOP/firmware/)

    # Copy device tree blobs
    (cd ${pkgs.raspberrypifw}/share/raspberrypi/boot && cp bcm2712*.dtb $NIX_BUILD_TOP/firmware/)

    # Copy DTB overlays
    mkdir -p $NIX_BUILD_TOP/firmware/overlays
    (cd ${pkgs.raspberrypifw}/share/raspberrypi/boot/overlays && cp *.dtbo $NIX_BUILD_TOP/firmware/overlays/)

    # Copy the kernel and initrd from the system closure
    mkdir -p $NIX_BUILD_TOP/firmware
    cp ${config.system.build.kernel}/kernel $NIX_BUILD_TOP/firmware/kernel.img
    cp ${config.system.build.initialRamdisk}/initrd $NIX_BUILD_TOP/firmware/initrd

    # Write kernel command line
    echo "${lib.concatStringsSep " " config.boot.kernelParams} init=${config.system.build.initialRamdisk}/init" > $NIX_BUILD_TOP/firmware/cmdline.txt

    # Copy config.txt (generated by nixos-hardware raspberry-pi configtxt module)
    cp ${config.hardware.raspberry-pi.configtxt.file} $NIX_BUILD_TOP/firmware/config.txt
  '';

  # Kernelboot does not use extlinux; force-override the default populateRootCommands
  # which would otherwise reference generic-extlinux-compatible.populateCmd.
  sdImage.populateRootCommands = lib.mkForce ''
    mkdir -p ./files/boot
  '';

  # Pi 5 EEPROM bootloader requires these config.txt settings:
  # Must be in [pi5] section for the firmware to recognize them.
  hardware.raspberry-pi.configtxt.settings.pi5 = {
    arm_64bit = 1;
    os_check = 0;
  };
}
