{ config, pkgs, ... }:

{
  imports = [
    ./rpi.nix
  ];

  # The default sd-image-aarch64.nix populateFirmwareCommands only copies
  # Pi 3/4 firmware (bcm2710/bcm2711 DTBs, U-Boot for Pi 3/4).
  # The Raspberry Pi 5 requires bcm2712 DTBs in the firmware partition
  # for the boot ROM to find the device tree.
  # The nixos-hardware raspberry-pi-5 module generates config.txt
  # via hardware.raspberry-pi.configtxt and uses generic-extlinux-compatible
  # (no U-Boot), so the firmware partition needs: boot blobs + bcm2712 DTBs + config.txt.
  sdImage.populateFirmwareCommands = ''
    # Firmware blobs (shared across all Pi models)
    (cd ${pkgs.raspberrypifw}/share/raspberrypi/boot && cp bootcode.bin fixup*.dat start*.elf $NIX_BUILD_TOP/firmware/)

    # Raspberry Pi 5 device tree blobs
    (cd ${pkgs.raspberrypifw}/share/raspberrypi/boot && cp bcm2712*.dtb $NIX_BUILD_TOP/firmware/)

    # config.txt generated by nixos-hardware raspberry-pi module
    cp ${config.hardware.raspberry-pi.configtxt.file} firmware/config.txt
  '';
}
